name: CI
on:
  push:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anishathalye/proof-html@v2
        with:
          directory: ./
          enforce_https: false
#          tokens: |
#            {"https://github.com": "${{ secrets.GITHUB_TOKEN }}"]
